/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminDashboardResponseDtoOutput } from '../../models/admin-dashboard-response-dto-output';

export interface AdminDashboardControllerGet$Params {
}

export function adminDashboardControllerGet(http: HttpClient, rootUrl: string, params?: AdminDashboardControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminDashboardResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, adminDashboardControllerGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminDashboardResponseDtoOutput>;
    })
  );
}

adminDashboardControllerGet.PATH = '/api/admin/dashboard';
