packages:
  - 'apps/*'
  - 'apps/*/*'
  - 'libs/*'
  - 'libs/*/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false # telemetry/analytics postinstall ping, not needed
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  prisma: true
  unrs-resolver: true
