/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SlotsResponseDtoOutput } from '../../models/slots-response-dto-output';

export interface SlotsControllerListSlots$Params {
}

export function slotsControllerListSlots(http: HttpClient, rootUrl: string, params?: SlotsControllerListSlots$Params, context?: HttpContext): Observable<StrictHttpResponse<SlotsResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, slotsControllerListSlots.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SlotsResponseDtoOutput>;
    })
  );
}

slotsControllerListSlots.PATH = '/api/slots';
