/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminUpdateOrderStatusDto } from '../../models/admin-update-order-status-dto';
import { AdminUpdateOrderStatusResponseDtoOutput } from '../../models/admin-update-order-status-response-dto-output';

export interface AdminOrdersControllerUpdateStatus$Params {
  id: string;
      body: AdminUpdateOrderStatusDto
}

export function adminOrdersControllerUpdateStatus(http: HttpClient, rootUrl: string, params: AdminOrdersControllerUpdateStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminUpdateOrderStatusResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, adminOrdersControllerUpdateStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminUpdateOrderStatusResponseDtoOutput>;
    })
  );
}

adminOrdersControllerUpdateStatus.PATH = '/api/admin/orders/{id}/status';
