/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrderDetailResponseDtoOutput } from '../../models/admin-order-detail-response-dto-output';

export interface AdminOrdersControllerDetail$Params {
  id: string;
}

export function adminOrdersControllerDetail(http: HttpClient, rootUrl: string, params: AdminOrdersControllerDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrderDetailResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, adminOrdersControllerDetail.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrderDetailResponseDtoOutput>;
    })
  );
}

adminOrdersControllerDetail.PATH = '/api/admin/orders/{id}';
