/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrderListResponseDtoOutput } from '../../models/admin-order-list-response-dto-output';

export interface AdminOrdersControllerList$Params {
  status?: 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
  dateFrom?: string;
  dateTo?: string;
  reference?: string;
  page?: number;
  pageSize?: number;
}

export function adminOrdersControllerList(http: HttpClient, rootUrl: string, params?: AdminOrdersControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrderListResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, adminOrdersControllerList.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('dateFrom', params.dateFrom, {});
    rb.query('dateTo', params.dateTo, {});
    rb.query('reference', params.reference, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrderListResponseDtoOutput>;
    })
  );
}

adminOrdersControllerList.PATH = '/api/admin/orders';
