/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrderDetailResponseDtoOutput } from '../../models/admin-order-detail-response-dto-output';
import { AssignCourierDto } from '../../models/assign-courier-dto';

export interface AdminOrdersControllerAssignCourier$Params {
  id: string;
      body: AssignCourierDto
}

export function adminOrdersControllerAssignCourier(http: HttpClient, rootUrl: string, params: AdminOrdersControllerAssignCourier$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrderDetailResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, adminOrdersControllerAssignCourier.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrderDetailResponseDtoOutput>;
    })
  );
}

adminOrdersControllerAssignCourier.PATH = '/api/admin/orders/{id}/courier';
