/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppControllerGetData$Params as AppControllerGetData$Params } from './fn/app/app-controller-get-data';
export { appControllerGetData as appControllerGetData } from './fn/app/app-controller-get-data';
export type { AuthControllerRegister$Params as AuthControllerRegister$Params } from './fn/auth/auth-controller-register';
export { authControllerRegister as authControllerRegister } from './fn/auth/auth-controller-register';
export type { AuthControllerVerifyOtp$Params as AuthControllerVerifyOtp$Params } from './fn/auth/auth-controller-verify-otp';
export { authControllerVerifyOtp as authControllerVerifyOtp } from './fn/auth/auth-controller-verify-otp';
export type { AuthControllerResendOtp$Params as AuthControllerResendOtp$Params } from './fn/auth/auth-controller-resend-otp';
export { authControllerResendOtp as authControllerResendOtp } from './fn/auth/auth-controller-resend-otp';
export type { AuthControllerLogin$Params as AuthControllerLogin$Params } from './fn/auth/auth-controller-login';
export { authControllerLogin as authControllerLogin } from './fn/auth/auth-controller-login';
export type { AuthControllerRefresh$Params as AuthControllerRefresh$Params } from './fn/auth/auth-controller-refresh';
export { authControllerRefresh as authControllerRefresh } from './fn/auth/auth-controller-refresh';
export type { AuthControllerLogout$Params as AuthControllerLogout$Params } from './fn/auth/auth-controller-logout';
export { authControllerLogout as authControllerLogout } from './fn/auth/auth-controller-logout';
export type { AuthControllerMe$Params as AuthControllerMe$Params } from './fn/auth/auth-controller-me';
export { authControllerMe as authControllerMe } from './fn/auth/auth-controller-me';
export type { CatalogControllerGetCatalog$Params as CatalogControllerGetCatalog$Params } from './fn/catalog/catalog-controller-get-catalog';
export { catalogControllerGetCatalog as catalogControllerGetCatalog } from './fn/catalog/catalog-controller-get-catalog';
