/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfirmDeliveryDto } from '../../models/confirm-delivery-dto';
import { CourierActionResponseDtoOutput } from '../../models/courier-action-response-dto-output';

export interface CouriersControllerConfirm$Params {
  id: string;
      body: ConfirmDeliveryDto
}

export function couriersControllerConfirm(http: HttpClient, rootUrl: string, params: CouriersControllerConfirm$Params, context?: HttpContext): Observable<StrictHttpResponse<CourierActionResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, couriersControllerConfirm.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CourierActionResponseDtoOutput>;
    })
  );
}

couriersControllerConfirm.PATH = '/api/couriers/deliveries/{id}/confirm';
