/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourierActionResponseDtoOutput } from '../../models/courier-action-response-dto-output';
import { MarkClientAbsentDto } from '../../models/mark-client-absent-dto';

export interface CouriersControllerMarkAbsent$Params {
  id: string;
      body: MarkClientAbsentDto
}

export function couriersControllerMarkAbsent(http: HttpClient, rootUrl: string, params: CouriersControllerMarkAbsent$Params, context?: HttpContext): Observable<StrictHttpResponse<CourierActionResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, couriersControllerMarkAbsent.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CourierActionResponseDtoOutput>;
    })
  );
}

couriersControllerMarkAbsent.PATH = '/api/couriers/deliveries/{id}/absent';
