/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourierTourResponseDtoOutput } from '../../models/courier-tour-response-dto-output';

export interface CouriersControllerTour$Params {
}

export function couriersControllerTour(http: HttpClient, rootUrl: string, params?: CouriersControllerTour$Params, context?: HttpContext): Observable<StrictHttpResponse<CourierTourResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, couriersControllerTour.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CourierTourResponseDtoOutput>;
    })
  );
}

couriersControllerTour.PATH = '/api/couriers/deliveries';
