/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderListResponseDtoOutput } from '../../models/order-list-response-dto-output';

export interface OrdersControllerList$Params {
  status?: 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
}

export function ordersControllerList(http: HttpClient, rootUrl: string, params?: OrdersControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderListResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, ordersControllerList.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderListResponseDtoOutput>;
    })
  );
}

ordersControllerList.PATH = '/api/orders';
