/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePaymentDto } from '../../models/create-payment-dto';
import { CreatePaymentResponseDtoOutput } from '../../models/create-payment-response-dto-output';

export interface OrdersControllerInitiatePayment$Params {
  id: string;
      body: CreatePaymentDto
}

export function ordersControllerInitiatePayment(http: HttpClient, rootUrl: string, params: OrdersControllerInitiatePayment$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatePaymentResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, ordersControllerInitiatePayment.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatePaymentResponseDtoOutput>;
    })
  );
}

ordersControllerInitiatePayment.PATH = '/api/orders/{id}/payment';
