/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateProfileDto } from '../../models/update-profile-dto';
import { UpdateProfileResponseDtoOutput } from '../../models/update-profile-response-dto-output';

export interface AuthControllerUpdateProfile$Params {
      body: UpdateProfileDto
}

export function authControllerUpdateProfile(http: HttpClient, rootUrl: string, params: AuthControllerUpdateProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateProfileResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerUpdateProfile.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateProfileResponseDtoOutput>;
    })
  );
}

authControllerUpdateProfile.PATH = '/api/auth/profile';
