/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangeEmailDto } from '../../models/change-email-dto';
import { ChangeEmailResponseDtoOutput } from '../../models/change-email-response-dto-output';

export interface AuthControllerChangeEmail$Params {
      body: ChangeEmailDto
}

export function authControllerChangeEmail(http: HttpClient, rootUrl: string, params: AuthControllerChangeEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<ChangeEmailResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerChangeEmail.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChangeEmailResponseDtoOutput>;
    })
  );
}

authControllerChangeEmail.PATH = '/api/auth/profile/email';
