/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordResetConfirmDto } from '../../models/password-reset-confirm-dto';
import { PasswordResetConfirmResponseDtoOutput } from '../../models/password-reset-confirm-response-dto-output';

export interface AuthControllerConfirmPasswordReset$Params {
      body: PasswordResetConfirmDto
}

export function authControllerConfirmPasswordReset(http: HttpClient, rootUrl: string, params: AuthControllerConfirmPasswordReset$Params, context?: HttpContext): Observable<StrictHttpResponse<PasswordResetConfirmResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerConfirmPasswordReset.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PasswordResetConfirmResponseDtoOutput>;
    })
  );
}

authControllerConfirmPasswordReset.PATH = '/api/auth/password-reset/confirm';
