/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerifyOtpDto } from '../../models/verify-otp-dto';
import { VerifyOtpResponseDtoOutput } from '../../models/verify-otp-response-dto-output';

export interface AuthControllerVerifyOtp$Params {
      body: VerifyOtpDto
}

export function authControllerVerifyOtp(http: HttpClient, rootUrl: string, params: AuthControllerVerifyOtp$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyOtpResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerVerifyOtp.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerifyOtpResponseDtoOutput>;
    })
  );
}

authControllerVerifyOtp.PATH = '/api/auth/otp/verify';
