/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangePhoneDto } from '../../models/change-phone-dto';
import { ChangePhoneResponseDtoOutput } from '../../models/change-phone-response-dto-output';

export interface AuthControllerChangePhone$Params {
      body: ChangePhoneDto
}

export function authControllerChangePhone(http: HttpClient, rootUrl: string, params: AuthControllerChangePhone$Params, context?: HttpContext): Observable<StrictHttpResponse<ChangePhoneResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerChangePhone.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChangePhoneResponseDtoOutput>;
    })
  );
}

authControllerChangePhone.PATH = '/api/auth/profile/phone';
