/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OtpResponseDtoOutput } from '../../models/otp-response-dto-output';

export interface AuthControllerResendOtp$Params {
}

export function authControllerResendOtp(http: HttpClient, rootUrl: string, params?: AuthControllerResendOtp$Params, context?: HttpContext): Observable<StrictHttpResponse<OtpResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerResendOtp.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OtpResponseDtoOutput>;
    })
  );
}

authControllerResendOtp.PATH = '/api/auth/otp/resend';
