/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordResetRequestDto } from '../../models/password-reset-request-dto';
import { PasswordResetRequestResponseDtoOutput } from '../../models/password-reset-request-response-dto-output';

export interface AuthControllerRequestPasswordReset$Params {
      body: PasswordResetRequestDto
}

export function authControllerRequestPasswordReset(http: HttpClient, rootUrl: string, params: AuthControllerRequestPasswordReset$Params, context?: HttpContext): Observable<StrictHttpResponse<PasswordResetRequestResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, authControllerRequestPasswordReset.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PasswordResetRequestResponseDtoOutput>;
    })
  );
}

authControllerRequestPasswordReset.PATH = '/api/auth/password-reset/request';
