/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgenciesResponseDtoOutput } from '../../models/agencies-response-dto-output';

export interface AgenciesControllerListAgencies$Params {
}

export function agenciesControllerListAgencies(http: HttpClient, rootUrl: string, params?: AgenciesControllerListAgencies$Params, context?: HttpContext): Observable<StrictHttpResponse<AgenciesResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, agenciesControllerListAgencies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AgenciesResponseDtoOutput>;
    })
  );
}

agenciesControllerListAgencies.PATH = '/api/agencies';
