/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddCartItemDto {
  articleTypeId?: string;
  instructions?: string;
  quantity: number;
  serviceId: string;
}
