/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminOrderDetailResponseDtoOutput {
  order: {
'id': string;
'reference': string;
'items': Array<{
'id': string;
'serviceId': string;
'serviceName': string;
'unit': 'PIECE' | 'KG';
'articleTypeId': string | null;
'articleTypeName': string | null;
'quantity': number;
'instructions': string | null;
'unitPriceXof': number;
'lineTotalXof': number;
}>;
'subtotalXof': number;
'discountXof': number;
'deliveryFeeXof': number;
'vatRateBps': number;
'vatAmountXof': number;
'totalXof': number;
'pickupType': 'HOME' | 'AGENCY';
'agencyId': string | null;
'agencyDropoffDate': string | null;
'pickupSlotId': string | null;
'deliverySlotId': string;
'deliveryCommune': string;
'deliveryQuartier': string;
'deliveryDetails': string;
'deliveryGeoLat': number | null;
'deliveryGeoLng': number | null;
'createdAt': string;
'status': 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
'statusHistory': Array<{
'fromStatus': 'DRAFT' | 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
'toStatus': 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
'reason': string | null;
'createdAt': string;
}>;
'payment': ({
'id': string;
'orderId': string;
'provider': 'CASH' | 'MOBILE_MONEY';
'status': 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED';
'amountXof': number;
'createdAt': string;
}) | null;
'invoice': ({
'id': string;
'number': string;
'issuedAt': string;
}) | null;
'clientName': string | null;
'clientPhone': string;
'clientEmail': string | null;
};
}
