/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminDashboardResponseDtoOutput {
  averageBasketXof: number;
  dailyRevenue: Array<{
'date': string;
'revenueXof': number;
'orders': number;
}>;
  revenue: {
'todayXof': number;
'last7DaysXof': number;
'last30DaysXof': number;
};
  statusCounts: Array<{
'status': 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
'count': number;
}>;
  topServices: Array<{
'serviceId': string;
'serviceName': string;
'quantity': number;
'revenueXof': number;
}>;
}
