/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminOrderListResponseDtoOutput {
  orders: Array<{
'id': string;
'reference': string;
'status': 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
'totalXof': number;
'itemsCount': number;
'createdAt': string;
'clientName': string | null;
'clientPhone': string;
}>;
  page: number;
  pageSize: number;
  total: number;
}
