/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCourierListResponseDtoOutput {
  couriers: Array<{
'id': string;
'fullName': string | null;
'phone': string;
}>;
}
