/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgenciesResponseDtoOutput {
  agencies: Array<{
'id': string;
'name': string;
'address': string;
'openingHours': string;
}>;
}
