/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthUserDtoOutput {
  email: string | null;
  id: string;
  phone: string;
  role: 'CLIENT' | 'STAFF' | 'COURIER' | 'ADMIN';
}
