/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartResponseDtoOutput {
  cart: {
'id': string | null;
'items': Array<{
'id': string;
'serviceId': string;
'serviceSlug': string;
'serviceName': string;
'unit': 'PIECE' | 'KG';
'articleTypeId': string | null;
'articleTypeName': string | null;
'quantity': number;
'instructions': string | null;
'unitPriceXof': number | null;
'lineTotalXof': number | null;
}>;
'subtotalXof': number | null;
'hasUnavailablePricing': boolean;
'pickupType': (('HOME' | 'AGENCY')) | null;
'agencyId': string | null;
'agencyDropoffDate': string | null;
'pickupSlotId': string | null;
'deliverySlotId': string | null;
'deliveryAddressId': string | null;
};
}
