/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CatalogResponseDtoOutput {
  categories: Array<{
'id': string;
'slug': string;
'name': string;
'position': number;
'services': Array<{
'id': string;
'slug': string;
'name': string;
'unit': 'PIECE' | 'KG';
'processingHours': number;
'prices': Array<{
'articleTypeId': string | null;
'articleTypeName': string | null;
'amountXof': number;
}>;
}>;
}>;
}
