/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePhoneResponseDtoOutput {
  demoOtpCode?: string;
  user: {
'id': string;
'fullName': string | null;
'email': string | null;
'phone': string;
'phoneVerified': boolean;
'notifyEmail': boolean;
'notifySms': boolean;
'role': 'CLIENT' | 'STAFF' | 'COURIER' | 'ADMIN';
};
}
