/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CheckoutResponseDtoOutput {
  order: {
'id': string;
'reference': string;
'status': 'PENDING_PICKUP';
'items': Array<{
'id': string;
'serviceId': string;
'serviceName': string;
'unit': 'PIECE' | 'KG';
'articleTypeId': string | null;
'articleTypeName': string | null;
'quantity': number;
'instructions': string | null;
'unitPriceXof': number;
'lineTotalXof': number;
}>;
'subtotalXof': number;
'discountXof': number;
'deliveryFeeXof': number;
'vatRateBps': number;
'vatAmountXof': number;
'totalXof': number;
'pickupType': 'HOME' | 'AGENCY';
'agencyId': string | null;
'agencyDropoffDate': string | null;
'pickupSlotId': string | null;
'deliverySlotId': string;
'deliveryCommune': string;
'deliveryQuartier': string;
'deliveryDetails': string;
'deliveryGeoLat': number | null;
'deliveryGeoLng': number | null;
'createdAt': string;
};
}
