/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourierTourResponseDtoOutput {
  deliveries: Array<{
'id': string;
'reference': string;
'clientName': string | null;
'clientPhone': string;
'deliveryCommune': string;
'deliveryQuartier': string;
'deliveryDetails': string;
'deliverySlotStartsAt': string | null;
'deliverySlotEndsAt': string | null;
'amountDueXof': number | null;
}>;
}
