/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourierActionResponseDtoOutput {
  orderId: string;
  status: 'PENDING_PICKUP' | 'PICKED_UP' | 'PROCESSING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED' | 'ON_HOLD';
}
