/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePaymentResponseDtoOutput {
  payment: {
'id': string;
'orderId': string;
'provider': 'CASH' | 'MOBILE_MONEY';
'status': 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED';
'amountXof': number;
'createdAt': string;
};
}
