/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAddressResponseDtoOutput {
  address: {
'id': string;
'label': string;
'commune': 'Cocody' | 'Plateau' | 'Marcory' | 'Treichville' | 'Yopougon' | 'Adjam\xE9' | 'Koumassi' | 'Port-Bou\xEBt';
'quartier': string;
'details': string;
'geoLat': number | null;
'geoLng': number | null;
'isDefault': boolean;
};
}
