/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginResponseDtoOutput {
  accessToken: string;
  user: {
'id': string;
'email': string | null;
'phone': string;
'role': 'CLIENT' | 'STAFF' | 'COURIER' | 'ADMIN';
};
}
