/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type SetPickupModeDto = ({
'pickupType': 'HOME';
} | {
'pickupType': 'AGENCY';
'agencyId': string;
'agencyDropoffDate': string;
});

