/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SlotsResponseDtoOutput {
  slots: Array<{
'id': string;
'date': string;
'startsAt': string;
'endsAt': string;
'capacity': number;
'seatsAvailable': number;
}>;
}
