/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAddressDto {
  commune?: 'Cocody' | 'Plateau' | 'Marcory' | 'Treichville' | 'Yopougon' | 'Adjam\xE9' | 'Koumassi' | 'Port-Bou\xEBt';
  details?: string;
  geoLat?: number;
  geoLng?: number;
  isDefault?: boolean;
  label?: string;
  quartier?: string;
}
