/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDtoOutput } from '../../models/cart-response-dto-output';

export interface CartControllerGetCart$Params {
}

export function cartControllerGetCart(http: HttpClient, rootUrl: string, params?: CartControllerGetCart$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, cartControllerGetCart.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDtoOutput>;
    })
  );
}

cartControllerGetCart.PATH = '/api/cart';
