/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddCartItemDto } from '../../models/add-cart-item-dto';
import { CartResponseDtoOutput } from '../../models/cart-response-dto-output';

export interface CartControllerAddItem$Params {
      body: AddCartItemDto
}

export function cartControllerAddItem(http: HttpClient, rootUrl: string, params: CartControllerAddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, cartControllerAddItem.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDtoOutput>;
    })
  );
}

cartControllerAddItem.PATH = '/api/cart/items';
