/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDtoOutput } from '../../models/cart-response-dto-output';
import { SetSlotsDto } from '../../models/set-slots-dto';

export interface CartControllerSetSlots$Params {
      body: SetSlotsDto
}

export function cartControllerSetSlots(http: HttpClient, rootUrl: string, params: CartControllerSetSlots$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, cartControllerSetSlots.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDtoOutput>;
    })
  );
}

cartControllerSetSlots.PATH = '/api/cart/slots';
