/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDtoOutput } from '../../models/cart-response-dto-output';
import { SetDeliveryAddressDto } from '../../models/set-delivery-address-dto';

export interface CartControllerSetDeliveryAddress$Params {
      body: SetDeliveryAddressDto
}

export function cartControllerSetDeliveryAddress(http: HttpClient, rootUrl: string, params: CartControllerSetDeliveryAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, cartControllerSetDeliveryAddress.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDtoOutput>;
    })
  );
}

cartControllerSetDeliveryAddress.PATH = '/api/cart/address';
