/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDtoOutput } from '../../models/cart-response-dto-output';

export interface CartControllerRemoveItem$Params {
  id: string;
}

export function cartControllerRemoveItem(http: HttpClient, rootUrl: string, params: CartControllerRemoveItem$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDtoOutput>> {
  const rb = new RequestBuilder(rootUrl, cartControllerRemoveItem.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDtoOutput>;
    })
  );
}

cartControllerRemoveItem.PATH = '/api/cart/items/{id}';
